version: '3.8'

services:
  catgpt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catgpt
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s